services:
  - type: web
    name: ajnabi-music
    runtime: python
    region: oregon # Ya singapore (closer to India)
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:8000 keep_alive:app & python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
